config/routes.rb
Rails.application.routes.draw do
  resources :posts
  root 'posts#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	before_action :find_post, only: [:show, :edit, :update, :destroy]
  def index
  	@post = Post.all.order("created_at DESC")
  end

  def new
  	@post = Post.new
  end

  def create
  	@post = Post.new(post_params)

  	if @post.save
  		redirect_to @post
  	else
  		render 'new'
  	end
  end

  def show
  	#@post = Post.find(params[:id])
  end

  def edit
  	#@post = Post.find(params[:id])
  end

  def update
  	# @post = Post.find(params[:id])

  	 if @post.update(post_params)
  	 	redirect_to @post
  	else
  		render 'edit'
  	 end
  end

  def destroy
  	# @post = Post.find(params[:id])

  	 @post.destroy
  	 redirect_to root_path
  end

  private

  def find_post
  	@post = Post.find(params[:id])
  end

  def post_params
  	params.require(:post).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= link_to "Home", root_path %>
  <%= link_to "New Post", new_post_path %>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
	<%= f.label :title %> <br>
	<%= f.text_field :title %> <br>
	<br>
	<%= f.label :body %> <br>
	<%= f.text_field :body %> <br>
	<br>
	<%= f.submit %>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<%= render 'form' %>

app/views/posts/index.html.erb
<% @post.each do |post| %>
	<h2><%= post.title %></h2>
	<div><%= truncate(post.body, :length => 35)%></div>
	<br>
	<%= link_to "Read Post", post %>
	<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>
<%= form_for @post do |f| %>
	<%= f.label :title %> <br>
	<%= f.text_field :title %> <br>
	<br>
	<%= f.label :body %> <br>
	<%= f.text_field :body %> <br>
	<br>
	<%= f.submit %>
<% end %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>

<div><%= @post.body %></div>

<%= link_to "Edit Post", edit_post_path(@post) %>


<%= link_to "Delete Post", post_path(@post), method: :delete, data: { confirm: "Are you sure?"} %>